param(
    [Parameter(Mandatory = $true)]
    [string]$RepositoryRoot,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$gitRevision = & git -C $RepositoryRoot rev-list --count HEAD 2>$null
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($gitRevision))
{
    throw "Could not determine the Git version for '$RepositoryRoot'."
}

$gitHash = & git -C $RepositoryRoot rev-parse --short=8 HEAD 2>$null
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($gitHash))
{
    throw "Could not determine the Git commit for '$RepositoryRoot'."
}

$releaseVersion = "r$($gitRevision.Trim())"

& git -C $RepositoryRoot diff-index --quiet HEAD -- 2>$null
$dirtyExitCode = $LASTEXITCODE
if ($dirtyExitCode -gt 1)
{
    throw "Could not determine the Git working tree state for '$RepositoryRoot'."
}

$exactTag = & git -C $RepositoryRoot describe --tags --exact-match --match $releaseVersion HEAD 2>$null
$isReleaseTag = $LASTEXITCODE -eq 0 -and $exactTag.Trim() -eq $releaseVersion
$isDirty = $dirtyExitCode -eq 1
$isCiRelease = $env:CODXE_RELEASE_BUILD -eq "1"

if ($isCiRelease -and $isDirty)
{
    throw "Refusing to create an official release version from a dirty working tree."
}

if (($isCiRelease -or $isReleaseTag) -and -not $isDirty)
{
    $gitVersion = $releaseVersion
}
else
{
    $gitVersion = "$releaseVersion-g$($gitHash.Trim())"
    if ($isDirty)
    {
        $gitVersion += "-dirty"
    }
}

$escapedGitVersion = $gitVersion.Replace("\", "\\").Replace('"', '\"')
$header = "// Auto-generated by MSBuild. Do not edit.`r`n#pragma once`r`n`r`n#define GIT_VERSION `"$escapedGitVersion`"`r`n"

$outputDirectory = [System.IO.Path]::GetDirectoryName($OutputPath)
[System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null

if ([System.IO.File]::Exists($OutputPath) -and [System.IO.File]::ReadAllText($OutputPath) -eq $header)
{
    Write-Host "GIT_VERSION=$gitVersion"
    exit 0
}

[System.IO.File]::WriteAllText($OutputPath, $header, [System.Text.Encoding]::ASCII)
Write-Host "GIT_VERSION=$gitVersion"
